
spring:
  application:
    name: service-discovery
server:
  port: ${PORT:8080}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: my-registry
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF